### ISSUE TITLE
Error hex

### ISSUE THREAD

**Issue by milnerjames** [Drew-Alleman/DataSurgeon#10]
please i get this error while running the command

cargo : The term 'cargo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:17 char:1
+ cargo build --release
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (cargo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

copy : Cannot find path 'C:\Users\Administrator\DataSurgeon\target\release\ds.exe' because it does not exist.
At line:24 char:1
+ copy "$(Get-Location)\target\release\ds.exe" $executablePath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...\release\ds.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by Drew-Alleman** [comment]
Hi,

Did this solve your issue? If you don't respond in the next couple of days I'm going to mark this as resolved, but if it's not truly resolved feel free to open a new ticket.

Best,
Drew
