### ISSUE TITLE
Suppress [*] Advisory

### ISSUE THREAD

**Issue by ssnkhan** [Drew-Alleman/DataSurgeon#3]
Hello, thanks for this tool. Just had a quick question, is it possible to suppress the `[*] Reading standard input. If you meant to analyze a file use 'ds -f <FILE>' (ctrl+c to exit)` advisory when running a command? e.g.,:

`wget -qO - https://threatview.io/Downloads/High-Confidence-CobaltStrike-C2%20-Feeds.txt | ds --clean -iTX | sort -V | uniq`

Also, why does `ds` installation prompt me for my password (on both macOS and Ubuntu)?

**Comment by Drew-Alleman** [comment]
No, not currently but I can make it an option later tonight. As for the sudo/password question. It needs admin privileges for the following line.
``` bash
sudo mv target/release/ds /usr/local/bin/ds
```
This line is used to move ds into the local bin, installing it so you can execute the command by using ```ds``` from anywhere in the command line. I removed some additional sudo lines that were used to delete the DataSurgeon directory. I will be leaving this open until I implement the option you suggested. Feel free to ask any more questions.

**Comment by Drew-Alleman** [comment]
I would also like to point out (for the sake of it) why the windows installer needs admin privileges. 
```powershell
setx PATH "$env:PATH;C:/ds/"
```
The line I have above is used to bind the location of the executable C:/ds/ds.exe to the user's path.  Allowing  you to execute the command by using ds from anywhere in the command line

**Comment by ssnkhan** [comment]
Thanks Drew! Re `sudo`, it might be worth prompting the user whether the installer should move the app to a directory within the `$PATH`. I realise now that this is set in https://github.com/Drew-Alleman/DataSurgeon/blob/a93663d0d06ae955a5d11f05f89cbca366adc5eb/install/install.sh#L7, but I imagine most users won't read the sh installer, and may be perturbed to enter their password.

**Comment by Drew-Alleman** [comment]
```
but I imagine most users won't read the sh installer, and may be perturbed to enter their password.
```
Good point. I will add a this to the roadmap.

**Comment by Drew-Alleman** [comment]
I added the option -S or --suppress to remove the warning message. Please let me know if you have any issues.

e.g
```
$ wget -qO - https://threatview.io/Downloads/High-Confidence-CobaltStrike-C2%20-Feeds.txt | ds --clean -iTSX | sort -V | uniq
206.189.201.57
206.189.236.243
212.8.251.167
212.113.106.118
217.79.243.148
```
```
$ wget -qO - https://threatview.io/Downloads/High-Confidence-CobaltStrike-C2%20-Feeds.txt | ds --clean -iTX | sort -V | uniq
213.227.154.170
213.227.154.235
216.244.71.155
217.79.243.148
[*] Reading standard input. If you meant to analyze a file use 'ds -f <FILE>' (ctrl+c to exit)
```
